export const ACTIVE_CAR = 'ACTIVE_CAR';

export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const RECEIVE_GET_USER = 'RECEIVE_GET_USER';

export const REQUEST_GET_USER_LIST = 'REQUEST_GET_USER_LIST';
export const RECEIVE_GET_USER_LIST = 'RECEIVE_GET_USER_LIST';
